# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

XCODEPROJ = 'FastlaneHuddle.xcodeproj'
WORKSPACE = 'FastlaneHuddle.xcworkspace'
SCHEME = 'FastLaneHuddle'

before_all do
  desc 'Ensuring git branch'
  ensure_git_branch
  ensure_git_status_clean
  yarn(
    command: 'create-changelog'
  )
end

# YARN LANES
lane :patch_release do
  yarn(
    command: 'version',
    flags: '--patch'
  )
  beta_release
end
lane :minor_release do
  yarn(
    command: 'version',
    flags: '--minor'
  )
  beta
end

lane :major_release do
  yarn(
    command: 'version',
    flags: '--major'
  )
  beta_release
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  private_lane :beta_relese do
    increment_build_number
    build_app(workspace: WORKSPACE, scheme: SCHEME)
    upload_to_testflight
  end
end
